VXC-2383-minor-feature/listar-e-importar-membros-vexpenses
felipeverse/desafio-tecnico pull request #6
Opened 2022-08-09 11:49 UTC by felipeverse

2022-08-11 11:30 UTC, eduardohenriquesousasilva commented on app/Http/Controllers/Vexpenses/MemberController.php
> +    public function index(IndexRequest $request)
Adicionar documentação do método

2022-08-11 11:31 UTC, eduardohenriquesousasilva commented on app/Http/Controllers/Vexpenses/MemberController.php
> +        $memberResponse = app(MemberServiceInterface::class)->retrieveMembers();
Está recebendo na request o search_name mas não está passando ele como argumento do método da service que irá fazer a busca, sugiro que passe ele ou caso não esteja utilizando que remova da FormRequest e do código, faz sentido?

2022-08-11 11:40 UTC, eduardohenriquesousasilva commented on app/Services/Vexpenses/MemberService.php
> +    public function retrieveMembers(string $searchName = ''): ServiceResponse
Aqui com sugestão, creio que fique melhor a sintaxe se vc utilizar valor null como default ao invés de '', as aspas ficam sendo uma string muito literal, o que acha?

2022-08-11 12:46 UTC, eduardohenriquesousasilva requested changes

2022-08-11 12:54 UTC, eduardohenriquesousasilva commented on app/Services/Vexpenses/MemberService.php
> +        foreach ($members as $key => $member) {
Utilizar a função map, do laravel ou o php a sua escolha

2022-08-11 15:00 UTC, felipeverse commented on app/Http/Controllers/Vexpenses/MemberController.php
> +    public function index(IndexRequest $request)
Nessa caso ele pode retornar uma View ou um Redirect, então não é necessário tipar, certo?

2022-08-11 16:42 UTC, felipeverse commented on app/Services/ContatoService.php
> +        try {
Quando formos revisar gostaria de tirar uma dúvida sobre os Rollbacks, pois no método sstoreMultiple da service de telefone eu utilizo o Rollback, a dúvida é só pra saber se não dá algum conflito ou redundância em usar ele nesta service e na outra.

2022-08-12 13:55 UTC, eduardohenriquesousasilva approved these changes

2022-08-12 13:55 UTC, merged